/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Orange LED -- GPIOD pin 13.
//	1 -- Led On
//	0 -- Led Off

int main(void) {
	uint32_t pin= 12;
	SystemInit();
   RCC->AHB1ENR |= BV(3);
   GPIOD->MODER &= ~BV((pin<<1) + 1);
   GPIOD->MODER |= BV(pin<<1);
   GPIOD->OTYPER &= ~BV(pin);
   GPIOD->OSPEEDR &= ~((BV((pin<<1) +1)) | BV(pin<<1));
   GPIOD->PUPDR &= ~((BV((pin<<1) +1)) | BV(pin<<1));

   while(1)
   {
	   GPIOD->BSRR |= BV(pin);
	   DelayMs(1000);
	   GPIOD->BSRR |= BV(28);
	   DelayMs(1000);
   }

	return 0;
}













