/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include "led.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


int main(void) {
    char str[32];
    int choice;
    SystemInit();
    UartInit(9600);
    gpio_led_init();

    while (1) {
        UartPuts("Menu:\r\n");
        UartPuts("1. Red Led On\r\n");
        UartPuts("2. Red Led Off\r\n");
        UartPuts("3. Blue Led On\r\n");
        UartPuts("4. Blue Led Off\r\n");
        UartPuts("Enter your choice: ");

        UartGets(str);
        sscanf(str, "%d", &choice);

        switch (choice) {
            case 1:
                turn_on_red_led();
                UartPuts("Red LED is ON\r\n");
                break;
            case 2:
                turn_off_red_led();
                UartPuts("Red LED is OFF\r\n");
                break;
            case 3:
                turn_on_blue_led();
                UartPuts("Blue LED is ON\r\n");
                break;
            case 4:
                turn_off_blue_led();
                UartPuts("Blue LED is OFF\r\n");
                break;
            default:
                UartPuts("Invalid choice\r\n");
                break;
        }
    }

    return 0;
}
