/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"
#include "uart.h"
#include<string.h>
#include<switch_inter.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

	void count_str(char *c);
	int main(void)
	{

		SystemInit();
		inituart(9600);
		SwitchInit();
		//uint8_t count = 0;
		uartputs("Sunbeam @ PG-DESD\r\n");
		char str[100];
	    while(1)
	    {
	    	while(switch_flag == 0)
	    		;
	    	DelayMs(500);
	        count++;

	    	sprintf(str, "count: %d\r\n", count);
	    	uartputs(str);
	    	//uartputs("\r\n");
	    	switch_flag = 0;


	    }


		return 0;

    /* Loop forever */
	//for(;;);
}
